-- MySQL Script generated by MySQL Workbench
-- Thu Jul 12 11:06:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proiect
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proiect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proiect` DEFAULT CHARACTER SET latin1 ;
USE `proiect` ;

-- -----------------------------------------------------
-- Table `proiect`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`users` (
  `Username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Gender` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`projects` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Manager` VARCHAR(20) NULL DEFAULT NULL,
  `Client` VARCHAR(45) NULL DEFAULT NULL,
  `ReleaseDate` DATETIME NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Manager_idx` (`Manager` ASC),
  CONSTRAINT `Manager`
    FOREIGN KEY (`Manager`)
    REFERENCES `proiect`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`taskstatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`taskstatuses` (
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`tasks` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TaskName` VARCHAR(45) NULL DEFAULT NULL,
  `ProjectID` INT(11) NULL DEFAULT NULL,
  `EstimatedTime` DATETIME NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ProjectID_idx` (`ProjectID` ASC),
  INDEX `tasks_Status_idx` (`Status` ASC),
  CONSTRAINT `tasks_ProjectID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `proiect`.`projects` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tasks_Status`
    FOREIGN KEY (`Status`)
    REFERENCES `proiect`.`taskstatuses` (`Status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`comments` (
  `TaskID` INT(11) NULL DEFAULT NULL,
  `Comment` VARCHAR(45) NULL DEFAULT NULL,
  `Username` VARCHAR(20) NULL DEFAULT NULL,
  `Date_Hour` DATETIME NULL DEFAULT NULL,
  INDEX `Comments_TaskID_idx` (`TaskID` ASC),
  INDEX `Comments_Username_idx` (`Username` ASC),
  CONSTRAINT `Comments_TaskID`
    FOREIGN KEY (`TaskID`)
    REFERENCES `proiect`.`tasks` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Comments_Username`
    FOREIGN KEY (`Username`)
    REFERENCES `proiect`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`files` (
  `TaskID` INT(11) NULL DEFAULT NULL,
  `File` BLOB NULL DEFAULT NULL,
  INDEX `TaskID_idx` (`TaskID` ASC),
  CONSTRAINT `files_TaskID`
    FOREIGN KEY (`TaskID`)
    REFERENCES `proiect`.`tasks` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`permissions` (
  `PermissionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PermissionName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`projectmembers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`projectmembers` (
  `ProjectID` INT(11) NULL DEFAULT NULL,
  `Username` VARCHAR(20) NULL DEFAULT NULL,
  INDEX `Username_idx` (`Username` ASC),
  INDEX `ProjectID_idx` (`ProjectID` ASC),
  CONSTRAINT `projectmembers_ProjectID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `proiect`.`projects` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `projectmembers_Username`
    FOREIGN KEY (`Username`)
    REFERENCES `proiect`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`taskworkers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`taskworkers` (
  `TaskID` INT(11) NULL DEFAULT NULL,
  `Username` VARCHAR(20) NULL DEFAULT NULL,
  INDEX `taskworkers_TaskID_idx` (`TaskID` ASC),
  INDEX `taskworkers_Username_idx` (`Username` ASC),
  CONSTRAINT `taskworkers_TaskID`
    FOREIGN KEY (`TaskID`)
    REFERENCES `proiect`.`tasks` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `taskworkers_Username`
    FOREIGN KEY (`Username`)
    REFERENCES `proiect`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proiect`.`userpermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proiect`.`userpermissions` (
  `Username` VARCHAR(20) NULL DEFAULT NULL,
  `PermissionName` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `userpermissions_Username_idx` (`Username` ASC),
  INDEX `userpermissions_PermissionName_idx` (`PermissionName` ASC),
  CONSTRAINT `userpermissions_PermissionName`
    FOREIGN KEY (`PermissionName`)
    REFERENCES `proiect`.`permissions` (`PermissionName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userpermissions_Username`
    FOREIGN KEY (`Username`)
    REFERENCES `proiect`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
